# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGc6CSJ-MwpMEWOyR85l9fcxwDOkbxac
"""

import streamlit as st
import pandas as pd
import re

# 1. 建立研究所甄試資訊資料集
admission_info = {
    "成功大學_數據科學研究所碩士班": {
        "錄取人數": "7名", "報名人數": "48名",
        "資料審查項目": ["大學歷年成績單", "自傳 (個人簡介、報考動機、對數據科學之認識、曾參與之研究及獎勵、社團活動等)", "研究計畫書", "其他有助於審查之相關資料 (如個案報告、研究成果等，至多提供3件)", "GRE、GMAT、英文能力測驗等", "推薦函二封"],
        "面試資訊": "審查成績通過者，再通知面試。面試佔總成績 60%。審查成績優異者得免面試優先錄取。"
    },
    "政治大學_科技管理與智慧財產研究所_智慧財產組": {
        "錄取人數": "9名", "報名人數": "47名",
        "資料審查項目": ["考生資料表", "學業成績總平均排名證明", "歷年成績單總表", "自傳及學習計畫", "其他有利審查資料 (如英文檢定、社團活動、各項考試競賽證明等)", "推薦信2份"],
        "面試資訊": "面試日期為 11月16日(星期日)。依資料審查加權後之成績擇優選取至多27名參加面試。"
    },
    "政治大學_法律學系_財經法組": {
        "錄取人數": "8名", "報名人數": "22名",
        "資料審查項目": ["學業成績總平均排名證明", "自傳 (含性格之自我分析、過去的教育經驗、未來生涯規劃)", "研究計畫", "其他有利審查資料 (如著作、國科會專題計畫、獎學金證明等)"],
        "面試資訊": "面試日期為 11月15日(星期六)下午。依資料審查加權後之成績擇優選取至多24名參加面試。"
    },
    "政治大學_資訊科學系_資訊科學與工程組(跨領域組)": {
        "錄取人數": "6名", "報名人數": "32名",
        "資料審查項目": ["考生備審資料摘要表 (需說明跨領域研究計畫)", "歷年成績單總表 (含系排名)", "其他有利審查資料 (如跨領域研究計畫、專題報告、競賽檢定證明等)", "推薦信2份"],
        "面試資訊": "面試日期為 11月13日(星期四)。依筆試(計算機概論)及審查資料加權後成績擇優選取至多2.5倍人數參加面試。"
    },
    "臺北大學_法律學系碩士班_財經法學組": {
        "錄取人數": "3名", "報名人數": "未知",
        "資料審查項目": ["報名表、身分證正反面、大學畢業證書", "學士班歷年成績單 (須註明歷年學業成績總平均之班排名百分比)", "自傳 (含簡歷及讀書計畫，限A4大小，4頁內)", "研究計畫 (含目錄、大綱及參考文獻，限A4大小，10頁內)", "其他有利審查資料", "※注意：勿附推薦函"],
        "面試資訊": "面試日期為 114年10月31日(星期五)。書面審查成績達80分且在該報考組別前6名以內(含)者，始得參加面試。"
    },
    "臺灣師範大學_資訊工程學系碩士班_跨領域組": {
        "錄取人數": "6名", "報名人數": "34名",
        "資料審查項目": ["大學歷年成績單正本1份 (須附名次證明並註明全班/組人數)", "研究計畫1份", "自傳1份", "師長推薦函2封", "其他有利審查之相關參考資料 (如專題報告、競賽成績等)"],
        "面試資訊": "甄試日期為 114年11月1日(星期六)上午8:00開始。初試(審查)及格者，始得參加複試(口試)。"
    },
    "臺灣科技大學_專利研究所碩士班": {
        "錄取人數": "10名", "報名人數": "24名",
        "資料審查項目": ["大學(專科)歷年成績單 (含名次證明)", "個人基本資料表", "自傳 (含進修計畫、研究方向、讀書計畫)", "推薦信 (至少1封)", "其他有助於審查之相關文件 (如英文能力證明、專題報告等)"],
        "面試資訊": "由審查成績擇優參加口試，口試名額以招生名額之二倍為原則。"
    },
    "清華大學_科技法律研究所碩士班_乙組(法律專業組)": {
        "錄取人數": "10名", "報名人數": "63名",
        "資料審查項目": ["大學歷年成績單", "推薦書2封", "學習研究計畫書 (格式自訂)", "自傳 (中文)", "個人資料表 (指定格式)", "英文能力證明", "其他有利申請之資料"],
        "面試資訊": "複試(口試)時間為 11月13日，地點為台積館。初試(審查)通過者始得參加複試。"
    },
    "陽明交通大學_科技法律研究所碩士班_甲組": {
        "錄取人數": "9名", "報名人數": "49名",
        "資料審查項目": ["【必繳】大學歷年成績單", "【必繳】名次證明書或研究工作證明書", "【必繳】自傳 (限5頁以內)", "【必繳】讀書計畫 (限5頁以內)", "【選繳】境外學歷證明、英文能力證明、其他有利審查文件、推薦函、同等學力證明"],
        "面試資訊": "口試日期為 114年11月9日(星期日)。依初試(書面審查)成績擇優參加複試。"
    },
    "東吳大學_法律學系碩士班_庚組(科技法律)": {
        "錄取人數": "6名", "報名人數": "20名",
        "資料審查項目": ["最高學歷證明文件", "最高學歷歷年成績單 (須附學業成績總平均及名次證明)", "個人簡歷表", "研究計畫", "自傳", "教師推薦函至少二封", "其他有利審查資料"],
        "面試資訊": "面試日期為 114年11月15日 (城中校區)。符合報考資格之報名考生皆需參加面試。"
    }
}

# 2. 自動計算錄取率 (%) 並更新字典
for school, info in admission_info.items():
    admitted_str = info.get("錄取人數", "0")
    applied_str = info.get("報名人數", "未知")

    # 使用正規表達式 (re) 提取字串中的數字
    admitted_match = re.search(r'\d+', admitted_str)
    applied_match = re.search(r'\d+', applied_str)

    if admitted_match and applied_match:
        admitted_num = int(admitted_match.group())
        applied_num = int(applied_match.group())

        if applied_num > 0:
            rate = (admitted_num / applied_num) * 100
            info["錄取率數值"] = rate
            info["錄取率"] = f"{rate:.1f}%"
    else:
        info["錄取率數值"] = -1
        info["錄取率"] = "資料不足(如人數未知)無法計算"

# ======== 以下為 Streamlit 網頁介面設計 ========

# 設定網頁標題與寬度
st.set_page_config(page_title="跨領域研究所推甄分析", layout="wide")
st.title("🎓 跨領域研究所推甄分析與查詢系統")

# 在側邊欄建立選單
menu = ["🔍 查詢特定校系", "📊 總覽與錄取率排行榜"]
choice = st.sidebar.radio("請選擇功能：", menu)

if choice == "🔍 查詢特定校系":
    st.header("校系詳細資訊查詢")

    # 建立下拉式選單
    school_names = list(admission_info.keys())
    selected_school = st.selectbox("👉 請選擇你想查詢的校系：", school_names)

    # 顯示選中的校系資訊
    info = admission_info[selected_school]
    st.subheader(f"✅ {selected_school}")

    # 使用欄位排版顯示數據
    col1, col2, col3 = st.columns(3)
    col1.metric("錄取人數", info['錄取人數'])
    col2.metric("報名人數", info['報名人數'])
    col3.metric("預估錄取率", info['錄取率'])

    st.markdown("---")
    st.write("**📝 資料審查項目：**")
    for item in info['資料審查項目']:
        st.write(f"- {item}")

    st.info(f"**🗣️ 面試資訊：** {info['面試資訊']}")

elif choice == "📊 總覽與錄取率排行榜":
    st.header("各校系數據總覽")

    # 將字典轉換為 Pandas DataFrame 方便在網頁上顯示表格
    df_data = []
    for school, info in admission_info.items():
        df_data.append({
            "校系名稱": school,
            "報名人數": info["報名人數"],
            "錄取人數": info["錄取人數"],
            "錄取率": info["錄取率"],
            "錄取率數值": info["錄取率數值"]
        })
    df = pd.DataFrame(df_data)

    # 排序並整理表格
    df_sorted = df.sort_values(by="錄取率數值", ascending=False).reset_index(drop=True)
    df_display = df_sorted[["校系名稱", "報名人數", "錄取人數", "錄取率"]]

    # 在網頁上顯示互動式表格
    st.dataframe(df_display, use_container_width=True)

# ======== 標籤與圓餅圖區塊 ========
    import plotly.express as px

    st.markdown("---")
    st.subheader("🥧 系所領域分佈圓餅圖")

    # 1. 定義標籤分類邏輯
    def assign_label(school_name):
        if "智財" in school_name or "專利" in school_name:
            return "智財"
        elif "財" in school_name:
            return "商法"
        elif "資" in school_name or "數" in school_name:
            return "科技"
        else:
            return "科法" # 處理清交東吳等剩餘的科法所

    # 2. 將標籤加入原本的 DataFrame 中
    df["領域標籤"] = df["校系名稱"].apply(assign_label)

    # 3. 計算各標籤的數量
    label_counts = df["領域標籤"].value_counts().reset_index()
    label_counts.columns = ["領域標籤", "數量"]

    # 4. 使用 plotly 繪製圓餅圖
    fig = px.pie(
        label_counts,
        values="數量",
        names="領域標籤",
        color_discrete_sequence=px.colors.sequential.Pastel # 使用柔和的顏色組合
    )

    # 5. 顯示圖表
    st.plotly_chart(fig, use_container_width=True)

